import {
  CalculateCommand,
  AppendCharacterCommand,
  ClearEntryCommand,
  ChangeSignCommand,
  ClearHistoryCommand,
  ClearAllCommand,
  BackspaceCommand,
} from '@/utils/commands'

export const btnTypes = [
  {
    type: 'operator',
    label: 'C',
    id: 'C',
    command: ClearEntryCommand,
  },
  {
    type: 'digit',
    label: '7',
    id: '7',
    command: AppendCharacterCommand,
  },
  {
    type: 'digit',
    label: '8',
    id: '8',
    command: AppendCharacterCommand,
  },
  {
    type: 'digit',
    label: '9',
    id: '9',
    command: AppendCharacterCommand,
  },
  {
    type: 'operator',
    label: '*',
    id: 'multiply',
    command: AppendCharacterCommand,
  },
  {
    type: 'operator',
    label: '-',
    id: 'subtract',
    command: AppendCharacterCommand,
  },
  {
    type: 'digit',
    label: '4',
    id: '4',
    command: AppendCharacterCommand,
  },
  {
    type: 'digit',
    label: '5',
    id: '5',
    command: AppendCharacterCommand,
  },
  {
    type: 'digit',
    label: '6',
    id: '6',
    command: AppendCharacterCommand,
  },
  {
    type: 'operator',
    label: '/',
    id: 'divide',
    command: AppendCharacterCommand,
  },
  {
    type: 'operator',
    label: '+',
    id: 'add',
    command: AppendCharacterCommand,
  },
  {
    type: 'digit',
    label: '1',
    id: '1',
    command: AppendCharacterCommand,
  },
  {
    type: 'digit',
    label: '2',
    id: '2',
    command: AppendCharacterCommand,
  },
  {
    type: 'digit',
    label: '3',
    id: '3',
    command: AppendCharacterCommand,
  },
  {
    type: 'calculate',
    label: '=',
    id: 'calculate',
    command: CalculateCommand,
  },
  {
    type: 'digit',
    label: '.',
    id: 'dot',
    command: AppendCharacterCommand,
  },
  {
    type: 'bracket',
    label: '(',
    id: 'leftBracket',
    command: AppendCharacterCommand,
  },
  {
    type: 'digit',
    label: '0',
    id: '0',
    command: AppendCharacterCommand,
  },
  {
    type: 'bracket',
    label: ')',
    id: 'rightBracket',
    command: AppendCharacterCommand,
  },
  {
    type: 'operator',
    label: '%',
    id: 'remainder',
    command: AppendCharacterCommand,
  },
  {
    type: 'operator',
    label: 'CA',
    id: 'CA',
    command: ClearAllCommand,
  },
  {
    type: 'sign',
    label: '+/-',
    id: 'sign',
    command: AppendCharacterCommand,
  },
  {
    type: 'backspace',
    label: '\u27F5',
    id: 'backspace',
    command: BackspaceCommand,
  },
]
