describe('Arithmetic', () => {
  beforeEach(() => {
    cy.visit('/')
  })
  it('add operation', () => {
    cy.get('.5')
      .click()
      .get('.add')
      .click()
      .get('.2')
      .click()
      .get('.calculate')
      .click()
      .get('.display')
      .should('have.text', '7')
  })
  it('subtract operation', () => {
    cy.get('.1')
      .click()
      .get('.0')
      .click()
      .get('.subtract')
      .click()
      .get('.4')
      .click()
      .get('.calculate')
      .click()
      .get('.display')
      .should('have.text', '6')
  })
  it('multiply operation', () => {
    cy.get('.4')
      .click()
      .get('.multiply')
      .click()
      .get('.3')
      .click()
      .get('.calculate')
      .click()
      .get('.display')
      .should('have.text', '12')
  })
  it('divide operation', () => {
    cy.get('.1')
      .click()
      .get('.4')
      .click()
      .get('.divide')
      .click()
      .get('.7')
      .click()
      .get('.calculate')
      .click()
      .get('.display')
      .should('have.text', '2')
  })
  it('remainder operation', () => {
    cy.get('.1')
      .click()
      .get('.3')
      .click()
      .get('.remainder')
      .click()
      .get('.5')
      .click()
      .get('.calculate')
      .click()
      .get('.display')
      .should('have.text', '3')
  })
  it('change sign operation', () => {
    cy.get('.1')
      .click()
      .get('.3')
      .click()
      .get('.subtract')
      .click()
      .get('.5')
      .click()
      .get('.sign')
      .click()
      .get('.display')
      .should('have.text', '13+5')
  })
})
