describe('History', () => {
  beforeEach(() => {
    cy.visit('/')
  })
  it('check adding to history', () => {
    cy.get('.5')
      .click()
      .get('.add')
      .click()
      .get('.2')
      .click()
      .get('.calculate')
      .click()
      .get('.history')
      .contains('5+2')
  })
  it('check removing from history', () => {
    cy.get('.5')
      .click()
      .get('.add')
      .click()
      .get('.2')
      .click()
      .get('.calculate')
      .click()
      .get('.CA')
      .click()
      .get('.history')
      .should('not.have.text', '5+2')
  })
})
